name: deck_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  path_provider: ^2.1.5
  drift: ^2.16.0
dev_dependencies:
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  