name: fanki
description: "A new Flutter project."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  flutter_bloc: ^9.0.0
  formz: ^0.8.0
  equatable: ^2.0.0
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
