name: anki_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  authentication_repository:
    path: packages/authentication_repository

  card_repository:
    path: packages/card_repository
  
  ai_service:
    path: packages/ai_service

  cupertino_icons: ^1.0.8

  provider: 6.1.5
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  uuid: ^4.3.3
  loading_animation_widget: ^1.2.1
  logging: ^1.0.0
  english_words: ^4.0.0
  firebase_auth: ^6.0.0
  shared_preferences: ^2.5.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  dart_openai: ^5.1.0
  file_picker: ^8.1.4
  syncfusion_flutter_pdf: ^30.1.42
  cached_network_image: ^3.4.1
  flutter_hooks: ^0.20.5
  flutter_markdown: ^0.7.4
  markdown: ^7.2.2
  flutter_math_fork: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets: 
    - assets/auth.json

  uses-material-design: true
